CREATE TABLE search (id INT AUTO_INCREMENT NOT NULL, query VARCHAR(255) NOT NULL, ip VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
CREATE TABLE deleted_reason (id INT AUTO_INCREMENT NOT NULL, msg VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
ALTER TABLE ads ADD deleted_reason_id INT DEFAULT NULL;
ALTER TABLE ads ADD CONSTRAINT FK_7EC9F62058B3E8E7 FOREIGN KEY (deleted_reason_id) REFERENCES deleted_reason (id);
CREATE INDEX IDX_7EC9F62058B3E8E7 ON ads (deleted_reason_id)
