iListFrontendBundle_anuncio:
        resource: "@iListFrontendBundle/Resources/config/routing/ad.yml"
        prefix:   /anuncio
        host:     "%base_host%"

iListFrontendBundle_account:
        resource: "@iListFrontendBundle/Resources/config/routing/account.yml"
        prefix:   /account
        host:     "%base_host%"

find_subcategory_by_category_id:
    path:  /buscaSubCategoria
    defaults: { _controller: iListFrontendBundle:Ad:getByCategoryId }

find_product_by_subcategory_id:
    path:  /buscaProduto
    defaults: { _controller: iListFrontendBundle:Ad:getBySubCategoryId }

ad_msg_send:
    path:  /enviar
    defaults: { _controller: iListFrontendBundle:Ad:sendAdMsg }

ad_reply_msg_send:
    path:  /reply_msg
    defaults: { _controller: iListFrontendBundle:Account:replyMsg }

find_address_by_zipcode:
    path:  /buscaCep/{zipcode}
    defaults: { _controller: iListFrontendBundle:Search:searchZipcode }

subdomain_search:
    path:     /{category_name}/{subcategory_name}
    host:     "{state}.%base_host%"
    defaults: { _controller: iListFrontendBundle:Search:index, category_name: '', subcategory_name: '', adtype: '', size: ''}
    requirements:
        state:  rj|mg

subdomain_vi:
    path:     /{city}/{category_name}/{slug}/{id}
    host:     "{state}.%base_host%"
    defaults: { _controller: iListFrontendBundle:Ad:viewAd }
    #requirements:
        #state:  rj|mg
    #requirements:
    #    domain: "%domain%"

home:
    path:  /
    defaults: { _controller: iListFrontendBundle:Default:index }


brasil_search:
    path:  /{category_name}/{subcategory_name}
    defaults: { _controller: iListFrontendBundle:Search:index, category_name: '', state: 'brasil', subcategory_name: '' }


