iListFrontendBundle_anuncio:
        resource: "@iListFrontendBundle/Resources/config/routing/ad.yml"
        prefix:   /anuncio
        #host:     "%base_host%"

iListFrontendBundle_account:
        resource: "@iListFrontendBundle/Resources/config/routing/account.yml"
        prefix:   /account
        #host:     "%base_host%"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    #host:     "%base_host%"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
    #host:     "%base_host%"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /cadastro
    #host:     "%base_host%"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.yml"
    prefix: /esqueci
    #host:     "%base_host%"

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    #host:     "%base_host%"


bomnegocio:
    path:  /bom
    defaults: { _controller: iListFrontendBundle:Default:bom }

find_subcategory_by_category_id:
    path:  /buscaSubCategoria
    defaults: { _controller: iListFrontendBundle:Ad:getByCategoryId }

find_color_by_category_id:
    path:  /buscaCor
    defaults: { _controller: iListFrontendBundle:Ad:getColorByCategoryId } 

find_size_by_category_id:
    path: /buscaSize
    defaults: { _controller: iListFrontendBundle:Ad:getSizeByCategoryId }

find_screen_by_category_id:
    path: /buscaScreen
    defaults: { _controller: iListFrontendBundle:Ad:getScreenByCategoryId }

find_processor_by_category_id:
    path: /buscaProcessador
    defaults: { _controller: iListFrontendBundle:Ad:getProcessorByCategoryId }

find_memory_by_category_id:
    path: /buscaMemory
    defaults: { _controller: iListFrontendBundle:Ad:getMemoryByCategoryId }

find_product_by_subcategory_id:
    path:  /buscaProduto
    defaults: { _controller: iListFrontendBundle:Ad:getBySubCategoryId }

ad_msg_send:
    path:  /enviar
    defaults: { _controller: iListFrontendBundle:Ad:sendAdMsg }

ad_reply_msg_send:
    path:  /reply_msg
    defaults: { _controller: iListFrontendBundle:Account:replyMsg }

find_address_by_zipcode:
    path:  /buscaCep/{zipcode}
    defaults: { _controller: iListFrontendBundle:Search:searchZipcode }

subdomain_search:
    path:     /{category_name}/{subcategory_name}
    host:     "{state}.%base_host%"
    defaults: { _controller: iListFrontendBundle:Search:index, category_name: '', subcategory_name: '', adtype: '', size: ''}
    requirements:
        state:  rj|mg

subdomain_vi:
    path:     /{city}/{category_name}/{slug}/{id}
    host:     "{state}.%base_host%"
    defaults: { _controller: iListFrontendBundle:Ad:viewAd }
    #requirements:
        #state:  rj|mg
    #requirements:
    #    domain: "%domain%"

home:
    path:  /
    defaults: { _controller: iListFrontendBundle:Default:index }


brasil_search:
    path:  /{category_name}/{subcategory_name}
    defaults: { _controller: iListFrontendBundle:Search:index, category_name: '', state: 'brasil', subcategory_name: '' }
    host:     "www.%base_host%"

