parameters:
#    i_list_frontend.example.class: iList\FrontendBundle\Example

services:
    ilist.twig.frontend_extension:
        class: iList\FrontendBundle\Twig\FrontendExtension
        tags:
            - { name: twig.extension }
