i_list_backend:
    resource: "@iListBackendBundle/Resources/config/routing.yml"
    prefix:   /admin



fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    host:     "%base_host%"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
    host:     "%base_host%"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /cadastro
    host:     "%base_host%"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.yml"
    prefix: /esqueci
    host:     "%base_host%"

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    host:     "%base_host%"

i_list_frontend:
    resource: "@iListFrontendBundle/Resources/config/routing.yml"
    prefix:   /