i_list_backend:
    resource: "@iListBackendBundle/Resources/config/routing.yml"
    prefix:   /admin

i_list_frontend:
    resource: "@iListFrontendBundle/Resources/config/routing.yml"
    prefix:   /

