

security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        chainprovider:
                chain:
                    providers: [fos_userbundle, fos_facebook_provider]
        fos_userbundle:
            id: fos_user.user_provider.username_email
        fos_facebook_provider:
            id: fos_facebook.user.login
        #dao_provider_by_id:
        #    entity: { class: YOUR_SECURITY_CLASS_NAME, property: id }

    firewalls:
        main:
            pattern: ^/
            fos_facebook:
                app_url: "http://apps.facebook.com/iList/"
                server_url: "http://www.ilist.dev/"
                login_path: /fb_login
                check_path: /fb_check
                #default_target_path: /login
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
                #http://symfony.com/doc/master/cookbook/security/remember_me.html
       # crosslogin:
       #     crosslogin: true
       #     provider: fos_userbundle
       #     request_matcher: crosslogin.session.matcher
        #    logout:
         #       path: /logout
         #       target: /
         #       invalidate_session: true
         #       handlers: [crosslogin.handler.logout]


    #factories:
    #    CrossLoginFactory: "%kernel.root_dir%/../src/FrontendBundle/Resources/config/security_factories.xml"


    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cadastro, role: ROLE_USER }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/account/, role: ROLE_USER }
        - { path: ^/anuncio/, role: ROLE_USER }
        - { path: ^/, role: ROLE_USER }


