i_list_backend_homepage:
    pattern:  /
    defaults: { _controller: iListBackendBundle:Default:index }

admin_login:
    pattern:   /login
    defaults:  { _controller: iListBackendBundle:Default:login }

admin_login_check:
    pattern:   /login_check

admin_logout:
    path:   /logout

iListBackendBundle_categoria:
        resource: "@iListBackendBundle/Resources/config/routing/category.yml"
        prefix:   /categoria

iListBackendBundle_subcategoria:
        resource: "@iListBackendBundle/Resources/config/routing/subcategory.yml"
        prefix:   /subcategoria

iListBackendBundle_produto:
        resource: "@iListBackendBundle/Resources/config/routing/product.yml"
        prefix:   /produto

iListBackendBundle_size:
        resource: "@iListBackendBundle/Resources/config/routing/size.yml"
        prefix:   /size

iListBackendBundle_color:
        resource: "@iListBackendBundle/Resources/config/routing/color.yml"
        prefix:   /color

iListBackendBundle_generation:
        resource: "@iListBackendBundle/Resources/config/routing/generation.yml"
        prefix:   /generation

iListBackendBundle_declinedmsg:
        resource: "@iListBackendBundle/Resources/config/routing/declinedmsg.yml"
        prefix:   /declinedmsg

iListBackendBundle_fila:
        resource: "@iListBackendBundle/Resources/config/routing/adqueue.yml"
        prefix:   /fila

iListBackendBundle_polegadas:
        resource: "@iListBackendBundle/Resources/config/routing/screensize.yml"
        prefix:   /polegadas

iListBackendBundle_processadores:
        resource: "@iListBackendBundle/Resources/config/routing/processor.yml"
        prefix:   /processadores

iListBackendBundle_memoriaram:
        resource: "@iListBackendBundle/Resources/config/routing/memoryram.yml"
        prefix:   /memoriaram