parameters:
#    i_list_backend.example.class: iList\BackendBundle\Example

#services:
#    i_list_backend.example:
#        class: %i_list_backend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    ilist_user.registration.form.type:
        class: iList\BackendBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: ilist_user_registration }