anuncio:
    pattern:  /
    defaults: { _controller: "iListFrontendBundle:Ad:index" }

anuncio_show:
    pattern:  /{id}/show
    defaults: { _controller: "iListFrontendBundle:Ad:show" }

anuncio_new:
    pattern:  /novoold
    defaults: { _controller: "iListFrontendBundle:Ad:new" }

anuncio_new_wizard:
    pattern:  /novo
    host:     "www.%base_host%"
    defaults: { _controller: "iListFrontendBundle:Ad:newWizard" }

anuncio_new_wizard_2:
    pattern:  /wizard2
    defaults: { _controller: "iListFrontendBundle:Ad:newWizard2" }

anuncio_create:
    pattern:  /criar
    defaults: { _controller: "iListFrontendBundle:Ad:create" }
    requirements: { _method: post }

anuncio_edit:
    pattern:  /{id}/editar
    defaults: { _controller: "iListFrontendBundle:Ad:edit" }

anuncio_update:
    pattern:  /{id}/update
    defaults: { _controller: "iListFrontendBundle:Ad:update" }
    requirements: { _method: post|put }

anuncio_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "iListFrontendBundle:Ad:delete" }
    requirements: { _method: post|delete }

anuncio_choose_reason:
    pattern:  /{id}/excluir
    defaults: { _controller: "iListFrontendBundle:Ad:chooseReason" }
    #requirements: { _method: post|delete }
